on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 50, +3.15
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +3.16
	of __del__(...)
	| garbage collecting SocketServer instance
