on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +3.96
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +4.97
	of handle_http_requests(...)
	| [192.168.0.8:51940] received 'GET / HTTP'
on ln. 41, +5.19
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.2
	of handle_http_requests(...)
	| [192.168.0.8:51942] received 'GET /get_r'
on ln. 41, +6.42
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +7.24
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.42
	of handle_http_requests(...)
	| [192.168.0.8:51944] received 'GET /favic'
on ln. 178, +8.24
	of handle_http_requests(...)
	| [192.168.0.8:51946] received 'GET /get_r'
on ln. 184, +8.24
	of handle_http_requests(...)
	| [192.168.0.8:51946] abruptly closed
on ln. 41, +8.24
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +9.03
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +9.24
	of handle_http_requests(...)
	| [192.168.0.8:51948] received 'GET /get_r'
on ln. 184, +9.24
	of handle_http_requests(...)
	| [192.168.0.8:51948] abruptly closed
on ln. 41, +9.24
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +10.03
	of handle_http_requests(...)
	| [192.168.0.8:51950] received 'POST /make'
on ln. 41, +10.04
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +10.24
	of handle_http_requests(...)
	| [192.168.0.8:51952] received 'GET /get_r'
on ln. 184, +10.24
	of handle_http_requests(...)
	| [192.168.0.8:51952] abruptly closed
on ln. 41, +10.24
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +11.05
	of handle_http_requests(...)
	| [192.168.0.8:51960] received 'GET /?erro'
on ln. 178, +11.09
	of handle_http_requests(...)
	| [192.168.0.8:51962] received 'GET /get_r'
on ln. 184, +11.09
	of handle_http_requests(...)
	| [192.168.0.8:51962] abruptly closed
on ln. 41, +11.12
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +12.12
	of handle_http_requests(...)
	| [192.168.0.8:51964] received 'GET /get_r'
on ln. 41, +12.31
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +13.17
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +13.32
	of handle_http_requests(...)
	| [192.168.0.8:51966] received 'GET /favic'
on ln. 178, +14.16
	of handle_http_requests(...)
	| [192.168.0.8:51970] received 'GET /get_r'
on ln. 184, +14.17
	of handle_http_requests(...)
	| [192.168.0.8:51970] abruptly closed
on ln. 41, +14.17
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +15.16
	of handle_http_requests(...)
	| [192.168.0.8:51972] received 'GET /get_r'
on ln. 184, +15.16
	of handle_http_requests(...)
	| [192.168.0.8:51972] abruptly closed
on ln. 41, +15.17
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +16.17
	of handle_http_requests(...)
	| [192.168.0.8:51974] received 'GET /get_r'
on ln. 184, +16.17
	of handle_http_requests(...)
	| [192.168.0.8:51974] abruptly closed
on ln. 41, +16.17
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +17.16
	of handle_http_requests(...)
	| [192.168.0.8:51976] received 'GET /get_r'
on ln. 184, +17.16
	of handle_http_requests(...)
	| [192.168.0.8:51976] abruptly closed
on ln. 41, +17.17
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 50, +17.55
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 178, +18.16
	of handle_http_requests(...)
	| [192.168.0.8:51978] received 'GET /get_r'
on ln. 184, +18.17
	of handle_http_requests(...)
	| [192.168.0.8:51978] abruptly closed
on ln. 59, +18.18
	of __del__(...)
	| garbage collecting SocketServer instance
