on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +7.26
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +8.26
	of handle_http_requests(...)
	| [192.168.0.8:44878] received 'GET /profi'
on ln. 41, +8.53
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +9.53
	of handle_http_requests(...)
	| [192.168.0.8:44880] received 'GET /favic'
on ln. 41, +12.28
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +13.28
	of handle_http_requests(...)
	| [192.168.0.8:44882] received 'GET /profi'
on ln. 41, +13.49
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +14.5
	of handle_http_requests(...)
	| [192.168.0.8:44884] received 'GET /favic'
on ln. 41, +32.73
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +33.74
	of handle_http_requests(...)
	| [192.168.0.8:44888] received 'GET /profi'
on ln. 41, +33.95
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +34.95
	of handle_http_requests(...)
	| [192.168.0.8:44890] received 'GET /favic'
on ln. 41, +63.85
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +64.85
	of handle_http_requests(...)
	| [192.168.0.8:44896] received 'GET /profi'
on ln. 41, +65.07
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +66.07
	of handle_http_requests(...)
	| [192.168.0.8:44898] received 'GET /favic'
on ln. 50, +106.56
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +106.57
	of __del__(...)
	| garbage collecting SocketServer instance
