on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +4.85
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +5.86
	of handle_http_requests(...)
	| [192.168.0.8:57106] received 'GET / HTTP'
on ln. 41, +6.43
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.44
	of handle_http_requests(...)
	| [192.168.0.8:57110] received 'GET /get_r'
on ln. 41, +7.6
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +8.51
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +8.6
	of handle_http_requests(...)
	| [192.168.0.8:57112] received 'GET /favic'
on ln. 178, +9.49
	of handle_http_requests(...)
	| [192.168.0.8:57114] received 'GET /get_r'
on ln. 184, +9.5
	of handle_http_requests(...)
	| [192.168.0.8:57114] abruptly closed
on ln. 41, +9.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +10.49
	of handle_http_requests(...)
	| [192.168.0.8:57118] received 'GET /get_r'
on ln. 184, +10.49
	of handle_http_requests(...)
	| [192.168.0.8:57118] abruptly closed
on ln. 41, +10.49
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +11.49
	of handle_http_requests(...)
	| [192.168.0.8:57120] received 'GET /get_r'
on ln. 184, +11.49
	of handle_http_requests(...)
	| [192.168.0.8:57120] abruptly closed
on ln. 41, +11.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +12.49
	of handle_http_requests(...)
	| [192.168.0.8:57122] received 'GET /get_r'
on ln. 184, +12.49
	of handle_http_requests(...)
	| [192.168.0.8:57122] abruptly closed
on ln. 41, +12.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +13.49
	of handle_http_requests(...)
	| [192.168.0.8:57124] received 'GET /get_r'
on ln. 184, +13.5
	of handle_http_requests(...)
	| [192.168.0.8:57124] abruptly closed
on ln. 41, +13.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +14.49
	of handle_http_requests(...)
	| [192.168.0.8:57126] received 'GET /get_r'
on ln. 184, +14.49
	of handle_http_requests(...)
	| [192.168.0.8:57126] abruptly closed
on ln. 41, +14.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +15.49
	of handle_http_requests(...)
	| [192.168.0.8:57128] received 'GET /get_r'
on ln. 184, +15.49
	of handle_http_requests(...)
	| [192.168.0.8:57128] abruptly closed
on ln. 41, +15.51
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +16.49
	of handle_http_requests(...)
	| [192.168.0.8:57130] received 'GET /get_r'
on ln. 184, +16.49
	of handle_http_requests(...)
	| [192.168.0.8:57130] abruptly closed
on ln. 41, +16.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +17.49
	of handle_http_requests(...)
	| [192.168.0.8:57132] received 'GET /get_r'
on ln. 184, +17.49
	of handle_http_requests(...)
	| [192.168.0.8:57132] abruptly closed
on ln. 41, +17.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +18.49
	of handle_http_requests(...)
	| [192.168.0.8:57134] received 'GET /get_r'
on ln. 184, +18.5
	of handle_http_requests(...)
	| [192.168.0.8:57134] abruptly closed
on ln. 41, +18.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +19.49
	of handle_http_requests(...)
	| [192.168.0.8:57136] received 'GET /get_r'
on ln. 184, +19.49
	of handle_http_requests(...)
	| [192.168.0.8:57136] abruptly closed
on ln. 41, +19.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 50, +19.82
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 178, +20.49
	of handle_http_requests(...)
	| [192.168.0.8:57138] received 'GET /get_r'
on ln. 184, +20.5
	of handle_http_requests(...)
	| [192.168.0.8:57138] abruptly closed
on ln. 59, +20.51
	of __del__(...)
	| garbage collecting SocketServer instance
