on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +2.66
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +3.66
	of handle_http_requests(...)
	| [192.168.0.8:46020] received 'GET /profi'
on ln. 41, +3.9
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +4.9
	of handle_http_requests(...)
	| [192.168.0.8:46022] received 'GET /favic'
on ln. 41, +6.4
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.41
	of handle_http_requests(...)
	| [192.168.0.8:46024] received 'POST /prof'
on ln. 41, +7.41
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +8.41
	of handle_http_requests(...)
	| [192.168.0.8:46026] received 'GET /profi'
on ln. 41, +8.61
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +9.61
	of handle_http_requests(...)
	| [192.168.0.8:46028] received 'GET /favic'
on ln. 41, +12.94
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +13.95
	of handle_http_requests(...)
	| [192.168.0.8:46030] received 'POST /prof'
on ln. 41, +13.96
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +14.96
	of handle_http_requests(...)
	| [192.168.0.8:46032] received 'GET /profi'
on ln. 41, +15.17
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +16.17
	of handle_http_requests(...)
	| [192.168.0.8:46034] received 'GET /favic'
on ln. 50, +28.22
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +28.23
	of __del__(...)
	| garbage collecting SocketServer instance
