on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +3.26
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +4.26
	of handle_http_requests(...)
	| [192.168.0.8:47262] received 'GET / HTTP'
on ln. 41, +15.41
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +16.42
	of handle_http_requests(...)
	| [192.168.0.8:47264] received 'GET / HTTP'
on ln. 50, +23.98
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +24.0
	of __del__(...)
	| garbage collecting SocketServer instance
