on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +1.78
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +2.79
	of handle_http_requests(...)
	| [192.168.0.8:44842] received 'GET /profi'
on ln. 41, +3.01
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +4.01
	of handle_http_requests(...)
	| [192.168.0.8:44844] received 'GET /favic'
on ln. 50, +4.13
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +4.15
	of __del__(...)
	| garbage collecting SocketServer instance
