on ln. 29, +0.0
	of __init__(...)
	| bound successfully to localhost:51820
on ln. 41, +3.41
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +5.42
	of handle_http_requests(...)
	| [127.0.0.1:35734] received 'GET / HTTP'
on ln. 41, +5.77
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +7.78
	of handle_http_requests(...)
	| [127.0.0.1:35738] received 'GET /favic'
on ln. 50, +10.2
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +10.22
	of __del__(...)
	| garbage collecting SocketServer instance
