on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +0.72
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +1.72
	of handle_http_requests(...)
	| [192.168.0.8:51914] received 'GET /get_r'
on ln. 184, +1.72
	of handle_http_requests(...)
	| [192.168.0.8:51914] abruptly closed
on ln. 41, +1.73
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +2.73
	of handle_http_requests(...)
	| [192.168.0.8:51916] received 'GET /get_r'
on ln. 41, +2.77
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +3.35
	of handle_http_requests(...)
	| [192.168.0.8:51918] received 'GET /get_r'
on ln. 184, +3.35
	of handle_http_requests(...)
	| [192.168.0.8:51918] abruptly closed
on ln. 41, +3.35
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +4.36
	of handle_http_requests(...)
	| [192.168.0.8:51920] received 'GET /get_r'
on ln. 41, +4.36
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +4.37
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +5.35
	of handle_http_requests(...)
	| [192.168.0.8:51924] received 'GET /get_r'
on ln. 184, +5.35
	of handle_http_requests(...)
	| [192.168.0.8:51924] abruptly closed
on ln. 41, +5.35
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +5.36
	of handle_http_requests(...)
	| [192.168.0.8:51922] received 'GET / HTTP'
on ln. 178, +5.43
	of handle_http_requests(...)
	| [192.168.0.8:51926] received 'GET /get_r'
on ln. 184, +5.43
	of handle_http_requests(...)
	| [192.168.0.8:51926] abruptly closed
on ln. 41, +5.45
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.47
	of handle_http_requests(...)
	| [192.168.0.8:51928] received 'GET /get_r'
on ln. 41, +6.68
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +7.51
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.68
	of handle_http_requests(...)
	| [192.168.0.8:51930] received 'GET /favic'
on ln. 41, +8.4
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +8.51
	of handle_http_requests(...)
	| [192.168.0.8:51932] received 'GET /get_r'
on ln. 184, +8.51
	of handle_http_requests(...)
	| [192.168.0.8:51932] abruptly closed
on ln. 41, +8.51
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +9.4
	of handle_http_requests(...)
	| [192.168.0.8:51934] received 'POST /make'
on ln. 178, +9.42
	of handle_http_requests(...)
	| [192.168.0.8:51936] received 'GET /get_r'
on ln. 184, +9.42
	of handle_http_requests(...)
	| [192.168.0.8:51936] abruptly closed
on ln. 50, +22.28
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +22.3
	of __del__(...)
	| garbage collecting SocketServer instance
