on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +5.7
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.7
	of handle_http_requests(...)
	| [192.168.0.8:44782] received 'GET /profi'
on ln. 41, +6.97
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.97
	of handle_http_requests(...)
	| [192.168.0.8:44784] received 'GET /favic'
on ln. 41, +24.03
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +25.04
	of handle_http_requests(...)
	| [192.168.0.8:44794] received 'GET /profi'
on ln. 41, +25.25
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +26.25
	of handle_http_requests(...)
	| [192.168.0.8:44796] received 'GET /favic'
on ln. 50, +35.94
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +35.95
	of __del__(...)
	| garbage collecting SocketServer instance
