on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +5.6
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.6
	of handle_http_requests(...)
	| [192.168.0.8:47368] received 'GET /regis'
on ln. 41, +6.88
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.88
	of handle_http_requests(...)
	| [192.168.0.8:47370] received 'GET /favic'
on ln. 41, +10.84
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +11.84
	of handle_http_requests(...)
	| [192.168.0.8:47372] received 'POST /regi'
on ln. 41, +11.85
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +12.85
	of handle_http_requests(...)
	| [192.168.0.8:47378] received 'GET /regis'
on ln. 41, +13.18
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +14.18
	of handle_http_requests(...)
	| [192.168.0.8:47380] received 'GET /favic'
on ln. 41, +18.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +19.5
	of handle_http_requests(...)
	| [192.168.0.8:47384] received 'POST /regi'
on ln. 41, +19.51
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +20.51
	of handle_http_requests(...)
	| [192.168.0.8:47386] received 'GET / HTTP'
on ln. 41, +20.81
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +21.81
	of handle_http_requests(...)
	| [192.168.0.8:47388] received 'GET /favic'
on ln. 41, +36.38
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +37.39
	of handle_http_requests(...)
	| [192.168.0.8:47392] received 'GET /profi'
on ln. 41, +37.67
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +38.67
	of handle_http_requests(...)
	| [192.168.0.8:47394] received 'GET /favic'
on ln. 50, +43.01
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +43.02
	of __del__(...)
	| garbage collecting SocketServer instance
