on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +4.52
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +5.52
	of handle_http_requests(...)
	| [192.168.0.8:47410] received 'GET / HTTP'
on ln. 41, +5.81
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.81
	of handle_http_requests(...)
	| [192.168.0.8:47412] received 'GET /favic'
on ln. 41, +6.85
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.85
	of handle_http_requests(...)
	| [192.168.0.8:47414] received 'GET /membe'
on ln. 41, +8.19
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +9.2
	of handle_http_requests(...)
	| [192.168.0.8:47416] received 'GET /favic'
on ln. 41, +11.18
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +12.18
	of handle_http_requests(...)
	| [192.168.0.8:47420] received 'POST /memb'
on ln. 41, +12.19
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +13.19
	of handle_http_requests(...)
	| [192.168.0.8:47422] received 'GET /membe'
on ln. 41, +13.5
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +14.5
	of handle_http_requests(...)
	| [192.168.0.8:47424] received 'GET /favic'
on ln. 50, +20.9
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +20.92
	of __del__(...)
	| garbage collecting SocketServer instance
