on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +2.85
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +3.85
	of handle_http_requests(...)
	| [192.168.0.8:49262] received 'GET / HTTP'
on ln. 41, +3.91
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +4.91
	of handle_http_requests(...)
	| [192.168.0.8:49264] received 'GET /index'
on ln. 41, +4.95
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +5.95
	of handle_http_requests(...)
	| [192.168.0.8:49266] received 'GET /get_r'
on ln. 41, +6.16
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +7.17
	of handle_http_requests(...)
	| [192.168.0.8:49268] received 'GET /favic'
on ln. 50, +80.76
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +80.77
	of __del__(...)
	| garbage collecting SocketServer instance
