on ln. 29, +0.0
	of __init__(...)
	| bound successfully to localhost:62854
on ln. 41, +8.86
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +10.88
	of handle_http_requests(...)
	| [127.0.0.1:39526] received 'GET / HTTP'
on ln. 41, +12.58
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +14.59
	of handle_http_requests(...)
	| [127.0.0.1:39530] received 'GET / HTTP'
on ln. 41, +15.0
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +17.0
	of handle_http_requests(...)
	| [127.0.0.1:39534] received 'GET /favic'
on ln. 41, +18.46
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +20.46
	of handle_http_requests(...)
	| [127.0.0.1:39538] received 'GET /index'
on ln. 41, +20.86
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +22.87
	of handle_http_requests(...)
	| [127.0.0.1:39542] received 'GET /favic'
on ln. 50, +55.36
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +55.38
	of __del__(...)
	| garbage collecting SocketServer instance
