on ln. 29, +0.0
	of __init__(...)
	| bound successfully to localhost:61643
on ln. 41, +8.27
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +10.28
	of handle_http_requests(...)
	| [127.0.0.1:36652] received 'GET / HTTP'
on ln. 41, +11.8
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +13.82
	of handle_http_requests(...)
	| [127.0.0.1:36656] received 'GET / HTTP'
on ln. 50, +34.17
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +34.19
	of __del__(...)
	| garbage collecting SocketServer instance
