on ln. 29, +0.0
	of __init__(...)
	| bound successfully to localhost:56569
on ln. 41, +8.14
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 149, +10.14
	of handle_http_requests(...)
	| [127.0.0.1:57398] received 'GET / HTTP'
on ln. 41, +10.8
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 149, +12.81
	of handle_http_requests(...)
	| [127.0.0.1:57402] received 'GET /favic'
on ln. 41, +15.48
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 149, +17.5
	of handle_http_requests(...)
	| [127.0.0.1:57406] received 'GET /404.h'
on ln. 41, +17.96
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 149, +19.97
	of handle_http_requests(...)
	| [127.0.0.1:57414] received 'GET /favic'
on ln. 50, +37.77
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +37.78
	of __del__(...)
	| garbage collecting SocketServer instance
